export const supplierData = {
  achievement: '供应商业绩',
  address: '联系地址',
  bankCount: '银行账号',
  coalLicence: '经营许可证编号',
  coalSource: '煤源存放地点、数量、质量',
  code: '供应商编号',
  coneMail: '联系人Email',
  corIdentity: '法人代表身份证',
  corPhone: '法人电话',
  corporation: '法人代表',
  creditLevel: '信誉等级',
  faxCode: '传真号码',
  financing: '注册资金',
  introduce: '供应商介绍',
  isStop: '是否停用',
  license: '经营执照编号',
  linkMan: '联系人',
  linkTel: '联系电话',
  membertypeid: '供应商类别',
  name: '供应商名称',
  norder: '顺序号',
  openBank: '开户银行',
  orgCode: '组织机构代码',
  postalCode: '邮政编码',
  ptAudit: '是否通过',
  regPlace: '公司注册地',
  shortName: '供应商简称',
  specIns: '特别说明',
  supplierid: '供应商ID',
  taxCode: '税务登记证编号',
  transMode: '运输方式及保障能力'
}
export const contractData = {
  acceptancemode: '验收方式',
  aparty: '合同甲方',
  applystatenum: '状态',
  attachment: 'url link',
  bparty: '合同乙方',
  contractid: '长协ID',
  contractnumber: '合同编号',
  deliverytime: '交货开始时间',
  deliverytimeend: '交货结束时间',
  operuser: '操作员',
  settlemode: '结算方式',
  signtime: '签署日期',
  transportMode: '运输方式'
}
export const userData = {
  address: '地址',
  email: '邮箱',
  idUser: '用户ID',
  job: '职位',
  name: '姓名',
  powerPlants: '所属电厂',
  roleId: '角色ID',
  username: '用户名'
}
